config/routes.rb
Pivotalharvested::Application.routes.draw do

  resources :people

  resources :projects  do
    member do
      post 'callback'
      get 'detail'
      post 'sync_stories'
    end
    collection do
      get 'reload'
      get 'new_link'
    end
  end

  resources :xero, only: [:index, :new] do
    collection do
        get 'purchase'
        get 'complete'
        post 'test'
    end
  end
  resources :person_mappings, only: [:destroy]

  root to: "home#index"
  resources :users, except: [:new, :index, :create] do
    member do
      get 'confirm_harvest'
    end
  end

  match 'harvest' =>'harvest#index'
  match 'integrations/:id/callback' => 'projects#callback'
  
  match 'logout' => 'home#logout'
  match 'auth/google_oauth2/callback' => 'home#google_oauth2'
  match 'auth/harvest/callback' => 'home#harvest'

  mount Hiro::Engine => "/hiro"
  mount Resque::Server, :at => "/resque"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email
  attr_accessible :harvest_id, :harvest_subdomain, :harvest_identifier, :harvest_secret
  attr_accessible :pivotal_id, :pivotal_token

  validates(:username, :presence => true)

  has_many :identities
  
  def to_s
    "#{username}"
  end

  def self.from_googleauth(auth)
    create(username: auth['info']['name'], email: auth['info']['email'])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(session[:user_id]|| params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(session[:user_id]|| params[:id])
  end

  def validate_pivotal_token
    return true unless @user.pivotal_token_changed?
    @current_user = @user
    pivotal_api.all_projects
    rescue => e 
      puts current_user.inspect
      puts e.inspect
      nil
  end

  def confirm_harvest
    redirect_to harvest_api.authorize_url(root_url)
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(session[:user_id]|| params[:id])
    @user.assign_attributes(params[:user])
    need_harvest_login = @user.harvest_subdomain_changed? || @user.harvest_identifier_changed? || @user.harvest_secret_changed?
    if validate_pivotal_token() && @user.save
      puts "user is valid"
      puts need_harvest_login
      if need_harvest_login
        redirect_to harvest_api.authorize_url(root_url)
      else
        redirect_to @user, notice: 'User was successfully updated.'
      end
    else
      @error = 'Wrong pivotal token.' if @user.pivotal_token_changed?
      render action: "edit"
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(session[:user_id]|| params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @error || notice %>
  <div class="alert alert-success">
    <%= @error ||= notice %>
    <a class="close" data-dismiss="alert" href="#">&times;</a>
  </div>
<% end %>

<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :username %>
    <%= f.input :pivotal_token %>
    <p class='small'>
  	 Get it from your pivotal tracker <%= link_to 'profile page', 'https://www.pivotaltracker.com/profile', {target: '_blank'} %><br>
	   Create oauth token for hipster at Account Settings -> Oauth Tokens
	   Please use <code><%= root_url %></code> as redirect url.
    </p>
    <%= f.input :harvest_subdomain %>
    <%= f.input :harvest_identifier %>
    <%= f.input :harvest_secret %>
  </div>

  <div class="form-submit">
    <%= f.button :submit %>
    <%= link_to 'Cancel', @user, class: 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row-fluid">
  <h2>Edit profile</h2>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="row-fluid">
  <h2>Profile</h2>
  <% if notice %>
  <div class="alert alert-success">
    <%= notice %>
    <a class="close" data-dismiss="alert" href="#">&times;</a>
  </div>
  <% end %>

  <div class="detail">
    <p>
      <b>Name</b>
      : <%= @user.username %>
    </p>

    <p>
      <b>Pivotal token</b>
      : <%= @user.pivotal_token %>
    </p>

    <p>
      <b>Harvest Subdomain</b>
      : <%= @user.harvest_subdomain %>
    </p>
    <p>
      <b>Harvest Identifier</b>
      : <%= @user.harvest_identifier %>
    </p>
    <p>
      <b>Harvest Secret</b>
      : <%= @user.harvest_secret %>
    </p>
  </div>

  <div class="form-submit">
    <%= link_to 'Confirm Harvest Connection', confirm_harvest_user_path(current_user), class: 'btn' %>
    <%= link_to 'Manage Project Integration', projects_path, class: 'btn' %>
    <%= link_to 'Edit', edit_user_path(@user), class: 'btn' %>
  </div>

</div>