config/routes.rb
Pivotalharvested::Application.routes.draw do

  resources :people

  resources :projects  do
    member do
      post 'callback'
      get 'detail'
      post 'sync_stories'
    end
    collection do
      get 'reload'
      get 'new_link'
    end
  end

  resources :xero, only: [:index, :new] do
    collection do
        get 'purchase'
        get 'complete'
        post 'test'
    end
  end
  resources :person_mappings, only: [:destroy]

  root to: "home#index"
  resources :users, except: [:new, :index, :create] do
    member do
      get 'confirm_harvest'
    end
  end

  match 'harvest' =>'harvest#index'
  match 'integrations/:id/callback' => 'projects#callback'
  
  match 'logout' => 'home#logout'
  match 'auth/google_oauth2/callback' => 'home#google_oauth2'
  match 'auth/harvest/callback' => 'home#harvest'

  mount Hiro::Engine => "/hiro"
  mount Resque::Server, :at => "/resque"
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  set_table_name 'integrations'

  belongs_to :user
  has_many :person_mappings, :dependent => :destroy, foreign_key: :integration_id
  has_many :people, :through => :person_mappings
  attr_accessible :harvest_project_id, :pivotal_project_id, :user_id
  attr_accessible :harvest_project_name, :pivotal_project_name
  attr_accessible :project_name, :client_id, :client_name
  attr_accessible :harvest_project_code, :harvest_billable, :harvest_budget
  attr_accessible :pivotal_start_iteration, :pivotal_start_date

  attr_accessible :person_ids, :create_method
  attr_accessor :person_ids, :create_method

  #For new project created through hipster
  with_options :if => :is_new_project? do |project|
    project.validates :project_name, :client_id, :pivotal_start_iteration, :pivotal_start_date, :presence => true
    project.validates :harvest_budget, :format => { :with => /^\d+??(?:\.\d{0,2})?$/ }, :numericality => {:greater_than => 0}
    project.validate :project_and_sprint_day_match

    project.after_validation :prepare_create
    
    project.before_create :project_created_at_pivotal_server
    project.before_create :project_created_at_harvest_server
    project.before_create :assign_person_mapping
  end

  #For existing harvest and pivotal project to integrate through hipster
  with_options :unless => :is_new_project? do |project|
    project.validates :harvest_project_id, :pivotal_project_id, :presence => true
    project.validates :harvest_project_id, :uniqueness => true
    project.validates :pivotal_project_id, :uniqueness => true

    project.before_create :retrieve_existing_project
    project.after_create :create_task_from_existing_project
  end
  
  before_update :assign_person_mapping

  def harvest_api
    @harvest_api ||= Api::HarvestClient.new(self.user)
  end

  def pivotal_api
    @pivotal_api ||= Api::PivotalClient.new(self.user)
  end

  def is_new_project?
    self.create_method.eql? 'new'
  end

  def project_and_sprint_day_match
    errors.add(:pivotal_start_iteration, " does not match project start date") unless Date.parse(self.pivotal_start_date).strftime("%A").eql? self.pivotal_start_iteration
  rescue ArgumentError
    #catch if the date format is invalid
    errors.add(:pivotal_start_date, " is invalid")
  end

  def project_created_at_pivotal_server
    start_date_formatted = Date.parse(self.pivotal_start_date).strftime("%m/%d/%Y")
    pivotal_project = pivotal_api.create_project(self.project_name, self.pivotal_start_iteration, start_date_formatted)
    p pivotal_project.inspect
    
    self.pivotal_project_id = pivotal_project.id
    errors.add(:project_name, ' Failed to create new project in Harvest') if pivotal_project.blank? || pivotal_project.id.blank?
  end

  def project_created_at_harvest_server
    harvest_project = harvest_api.create_project(self)

    self.harvest_project_id = harvest_project.id
    errors.add(:project_name, ' Failed to create new project in Harvest') if harvest_project.blank? || harvest_project.id.blank?
  end

  def prepare_create
    self.harvest_project_name = self.project_name
    self.pivotal_project_name = self.project_name
  end

  def retrieve_existing_project
    harvest_project = harvest_api.find_project(self.harvest_project_id)
    pivotal_project = pivotal_api.find_project(self.pivotal_project_id)

    self.client_id = harvest_project.client_id
    
    self.pivotal_project_name = pivotal_project.name
    self.pivotal_start_iteration = pivotal_project.week_start_day
    self.pivotal_start_date = pivotal_project.start_date 

    self.harvest_project_name = harvest_project.name
    self.harvest_billable = harvest_project.billable.to_s
    self.harvest_budget = harvest_project.cost_budget
    self.harvest_project_code = harvest_project.code

    self.project_name = pivotal_project.name
  end

  def create_task_from_existing_project
    #ambil semua task
    stories = pivotal_api.list_all_story_by_project(self.pivotal_project_id)
    tasks = harvest_api.all_tasks.map(&:name)
    harvest_id = harvest_api.get_project_manager_harvest_id(self.harvest_project_id)
    #loop buat task di harvest
    #CREATE task story
    stories.each do |story|
      tmp = "[##{story.id}] #{story.name}"
      if !tasks.include? tmp
        task = harvest_api.create(tmp, self.harvest_project_id, harvest_id)
        TaskStory.create(task_id: task.id, story_id: story.id)
      end
    end
  end

  def assign_person_mapping
    pivotal_api
    project_member = []
    self.person_ids.each do |mapping_id|
      person = Person.find(mapping_id)

      membership = PivotalTracker::Membership.new(:role => "Member", :name => person.pivotal_name, :email => person.pivotal_email)
      pivotal_project = PivotalTracker::Project.new
      pivotal_project.id = self.pivotal_project_id
      membership = membership.assign(pivotal_project)

      user_assignment = harvest_api.assign_user(self.harvest_project_id, person.harvest_id)

      project_member << person
    end unless self.person_ids.blank?
    self.people = self.people + project_member
  end

  def to_s
    "#{harvest_project_name} - #{pivotal_project_name}"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  CACHE_PERIODE = 3.minutes
  before_filter :find_user, except: [:callback, :reload]
  before_filter :initialize_callback, only: [:callback]

  def find_user
    @user = current_user
    if @user.nil? || @user.harvest_secret.blank? || @user.harvest_subdomain.blank? || @user.harvest_identifier.blank? || @user.pivotal_token.blank?
      redirect_to edit_user_path(@user), notice: "Incomplete user profile"
    end
    @user
  end

  def reload
    Rails.cache.clear
    redirect_to root_url
  end

  def fetch_clients
    @harvest_clients ||= harvest_api.cached_clients
  end

  def fetch_projects
    @harvest_projects ||= harvest_api.cached_projects.select do |project_entry|
          Project.where(harvest_project_id: project_entry.id).first.nil?
      end
    @pivotal_projects ||= pivotal_api.cached_projects.select do |project_entry|
          Project.where(pivotal_project_id: project_entry.id).first.nil?
      end
  end

  def store(activity)
    puts "#{params[:id]} - #{activity.instance_variables.inspect}"
  end

  def find_task_for_story(story_id)
    @task_story ||= TaskStory.where(story_id: story_id).first
    @task_story.try(:task_id)
  end

  def initialize_callback
    @project = Project.find(params[:id])
    @current_user = @project.user
  end

  def callback
    activity = ActivityParam.new(params)
    harvest_user = @project.people.where(pivotal_name: activity.author).first
    harvest_id = harvest_user.harvest_id unless harvest_user.nil?

    case activity.type
    when ActivityParam::CREATE_STORY
      harvest_id ||= harvest_api.get_project_manager_harvest_id(@project.harvest_project_id)
      puts "Using harvest id #{harvest_id}"
      task = harvest_api.create(activity.task_name, @project.harvest_project_id, harvest_id)
      TaskStory.create(task_id: task.id, story_id: activity.story_id)
    when ActivityParam::START_STORY
      task_id = find_task_for_story(activity.story_id)
      harvest_api.start_task(task_id, @project.harvest_project_id, harvest_id) unless harvest_id.blank?
    when ActivityParam::FINISH_STORY
      task_id = find_task_for_story(activity.story_id)
      harvest_api.stop_task(task_id, harvest_id) unless harvest_id.blank?
    else
      # do nothing just log it
    end
    # persist activity param incase we need it in the future
    store(activity)
    head :no_content
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    
    render :template => "layouts/webhook", :layout => nil
  end

  def detail
    @project = Project.find(params[:id])
    render "show"
  end

  def find_people_list
    @people_list ||= Person.all
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new(user_id: current_user.id)
    find_people_list
    fetch_clients

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  def edit
    @project = Project.find(params[:id])
    find_people_list.select! do |person| 
      !@project.people.include? person
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new_link
  # GET /projects/new_link.json
  def new_link
    @project = Project.new(user_id: current_user.id)
    fetch_projects

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to project_path(@project), notice: 'Project had been created successfully.'
    else
      find_people_list
      fetch_clients
      render action: "new"
    end
  end

   # POST /projects
  # POST /projects.json
  def update
    @project = Project.find(params[:id])
    @project.person_ids = params[:project][:person_ids]

    if @project.save
      redirect_to detail_project_path(@project), notice: 'Project had been updated successfully.'
    else
      find_people_list.select! do |person| 
        !@project.people.include? person
      end
      render action: "edit"
    end
  end

  def sync_stories
    Resque.enqueue(SyncStoriesJob, params[:id])
    redirect_to projects_url, notice: 'Syncronization request has been scheduled successfully in background'
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

class ActivityParam
  CREATE_STORY = 0
  START_STORY = 1
  FINISH_STORY = 2

  attr_accessor :id, :event_type, :project_id, :author, :description, :story_id, :story_name, :story_state
  def initialize params={}
    self.id = params[:id]
    params = params[:activity]
    self.event_type = params[:event_type]
    self.project_id = params[:project_id]
    self.author = params[:author]
    self.description = params[:description]
    self.story_id = params[:stories][0][:id]
    self.story_name = params[:stories][0][:name]
    self.story_state = params[:stories][0][:current_state]
  end

  def type
    if event_type == 'story_create'
      return CREATE_STORY
    end

    if event_type == 'story_update'
      case story_state
      when 'started'
        return START_STORY
      when 'finished'
        return FINISH_STORY
      end
    end
  end

  def task_name
    "[##{story_id}] #{story_name}"
  end
end

app/views/projects/_form.html.erb
<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
    <a class="close" data-dismiss="alert" href="#">&times;</a>
  </div>
<% end %>
<hr>
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div valign="center">
      <%= f.input :client_id, as: :select, collection: @harvest_clients %>
      <%= f.input :project_name %>
      <%= f.input :harvest_project_code, :label => 'Project Code' %>
      <%= f.input :harvest_billable, as: :select, :label => 'Billable' %>
      <%= f.input :harvest_budget, :label => 'Budget ($)' %>
      <%= f.input :pivotal_start_iteration, as: :select, :label => 'Start Iteration', collection: Date::DAYNAMES.zip(Date::DAYNAMES) %>
      <%= f.input :pivotal_start_date, :label => 'Start Date' %>
    <br> <b>Team Member</b>
    <% if @people_list.empty? %>
      <br>No user found
    <% else %>
      <% @people_list.each do |pm| %>
        <div><input type="checkbox" name="project[person_ids][]" id="project_person_ids" value="<%=pm.id%>" /> <%=pm.harvest_name%></div>
      <% end %>
    <% end %>
    <%= f.association :user, as: :hidden %>
    <%= f.hidden_field :create_method, :value => 'new' %>
  </div>
  <div class="form-submit">
    <%= f.button :submit, :value => 'Create Project' %>

    <% if @project.id %>
      <%= link_to 'Cancel', detail_project_path(@project.id), class: 'btn' %>
    <% else %>
      <%= link_to 'Cancel', projects_path, class: 'btn' %>
    <% end %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="row-fluid">
  <h2>Assign Member</h2>

<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="detail">
    <p>
      <b>Project Name</b>
      : <%= @project.project_name %>
    </p>

    <p>
      <b>Harvest Project</b>
      : <%= @project.harvest_project_id %> - <%= @project.harvest_project_name %>
    </p>

    <p>
      <b>Pivotal Project</b>
      : <%= @project.pivotal_project_id %> - <%= @project.pivotal_project_name %>
    </p>
  </div>

  <div class="form-inputs">
  <% if @people_list.empty? %>
      <br>No user found
    <% else %>
      <% @people_list.each do |pm| %>
        <div><input type="checkbox" name="project[person_ids][]" id="project_person_ids" value="<%=pm.id%>" /> <%=pm.harvest_name%></div>
      <% end %>
    <% end %>
    
  </div>

  <div class="form-submit">
    <%= f.button :submit, :label => 'Assign' %>

    <%= link_to 'Cancel', detail_project_path(@project), class: 'btn' %>
  </div>
<% end %>
</div>

app/views/projects/index.html.erb
<div class="row-fluid">
  <h2>Projects</h2>
 <% if notice %>
  <div class="alert alert-success">
    <%= notice %>
    <a class="close" data-dismiss="alert" href="#">&times;</a>
  </div>
<% end %>
 <% if @projects.empty? %>
 <p>No Projects found</p>
 <% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Harvest project</th>
        <th>Pivotal project</th>
        <th>User</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

  <% @projects.each do |project| %>
      <tbody>
        <tr>
        <td><%= project.harvest_project_id %> - <%= project.harvest_project_name %></td>
        <td><%= project.pivotal_project_id %> - <%= project.pivotal_project_name %></td>
        <td><%= project.user %></td>
        <td><%= link_to 'Show', detail_project_path(project.id) if project.user.id==@user.id %></td>
        <td><%= link_to 'Sync Stories', sync_stories_project_path(project.id), method: :post, data: { confirm: "Are you sure? \nThis should not be a used as regular instruction as it would take significant resources on background." } if project.user.id==@user.id %></td>
        <td><%= link_to 'Destroy', project_path(project.id), method: :delete, data: { confirm: "Are you sure? \nThe project in harvest and pivotal tracker will remain unchanged." } if project.user.id==@user.id %></td>
      </tr>
      </tbody>
  <% end %>
  </table>

  <% end %>
  <%= link_to 'New Project', new_project_path, class: 'btn' %>
  <%= link_to 'Link Existing Project', new_link_projects_path, class: 'btn' %>
</div>

app/views/projects/new.html.erb
<div class="row-fluid">
  <h2>Create Project</h2>
  <%= render 'form' %>
</div>

app/views/projects/new_link.html.erb
<div class="row-fluid">
  <h2>Integrate Existing Project</h2>
  <% if notice %>
  <div class="alert alert-success">
    <%= notice %>
    <a class="close" data-dismiss="alert" href="#">&times;</a>
  </div>
<% end %>
<hr>
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :harvest_project_id, as: :select, collection: @harvest_projects %>
    <%= f.input :pivotal_project_id, as: :select, collection: @pivotal_projects %>
   
    <%= f.association :user, as: :hidden %>
    <%= f.hidden_field :create_method, :value => 'existing' %>
  </div>
  <div class="form-submit">
    <%= f.button :submit, :value => 'Link Project' %>

    <% if @project.id %>
      <%= link_to 'Cancel', detail_project_path(@project.id), class: 'btn' %>
    <% else %>
      <%= link_to 'Cancel', projects_path, class: 'btn' %>
    <% end %>
  </div>
<% end %>
</div>

app/views/projects/show.html.erb
<div class="row-fluid">
  <h2>Project</h2>
  <% if notice %>
  <div class="alert alert-success">
    <%= notice %>
    <a class="close" data-dismiss="alert" href="#">&times;</a>
  </div>
  <% end %>

  <div class="detail">
    <p>
      <b>Project Name</b>
      : <%= @project.project_name %>
    </p>

    <p>
      <b>Harvest Project</b>
      : <%= @project.harvest_project_id %> - <%= @project.harvest_project_name %>
    </p>

    <p>
      <b>Pivotal Project</b>
      : <%= @project.pivotal_project_id %> - <%= @project.pivotal_project_name %>
    </p>

    <p>
      <b>Project Code</b>
      : <%= @project.harvest_project_code %>
    </p>

     <p>
      <b>Billable</b>
      : <%= @project.harvest_billable %>
    </p>

     <p>
      <b>Budget</b>
      : <%= @project.harvest_budget %>
    </p>

     <p>
      <b>Start Iteration</b>
      : <%= @project.pivotal_start_iteration %>
    </p>

     <p>
      <b>Start Date</b>
      : <%= @project.pivotal_start_date %>
    </p>

    <p>
      <b>Project Manager</b>
      : <%= @project.user %>
    </p>

    <p>
      <b>Callback</b>
      : <%= callback_project_url(@project) %>
    </p>
  </div>

<div class="row-fluid">
  <h2>Project Member</h2>

<% if @project.person_mappings.empty? %>
  No Member found.
<% else %>
<table class="table">
    <thead>
      <tr>
        <th>Harvest</th>
        <th>Pivotal</th>
        <th></th>
      </tr>
    </thead>

  <% @project.person_mappings.each do |mapping| %>
    <tbody>
      <tr>
        <td><%= mapping.person.harvest_info %></td>
        <td><%= mapping.person.pivotal_info %></td>   
        <td><%= link_to 'Remove', mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </tbody>
  <% end %>
  </table>
  <% end %>
</div>
  <div class="form-submit">
    <%= link_to 'Assign Member', edit_project_path(@project), class: 'btn' %>
    <%= link_to 'Back', projects_path, class: 'btn' %>
  </div>
  <br/>
</div>