config/routes.rb
Pivotalharvested::Application.routes.draw do

  resources :people

  resources :projects  do
    member do
      post 'callback'
      get 'detail'
      post 'sync_stories'
    end
    collection do
      get 'reload'
      get 'new_link'
    end
  end

  resources :xero, only: [:index, :new] do
    collection do
        get 'purchase'
        get 'complete'
        post 'test'
    end
  end
  resources :person_mappings, only: [:destroy]

  root to: "home#index"
  resources :users, except: [:new, :index, :create] do
    member do
      get 'confirm_harvest'
    end
  end

  match 'harvest' =>'harvest#index'
  match 'integrations/:id/callback' => 'projects#callback'
  
  match 'logout' => 'home#logout'
  match 'auth/google_oauth2/callback' => 'home#google_oauth2'
  match 'auth/harvest/callback' => 'home#harvest'

  mount Hiro::Engine => "/hiro"
  mount Resque::Server, :at => "/resque"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hipster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/logo.png">
</head>
<body>

  <div class="container-narrow">
    <div class="masthead">
      <ul class="nav nav-pills pull-right">
        <li><%= link_to "Home", main_app.root_url, class: 'btn' %></li>
      <% if current_user %>
        <li><%= link_to 'Reload Data', main_app.reload_projects_path, class: 'btn' %></li>
        <li><%= link_to "Profile", main_app.user_path(current_user.id), class: 'btn' %></li>
        <li><%= link_to 'People', main_app.people_path, class: 'btn' %></li>
        <% if Object.const_defined?('Hiro') %>
          <li><%= link_to "Hiro", '/hiro', class: 'btn' %></li>
          <li><%= link_to "Bank Statement", '/hiro/bank_statements', class: 'btn' %></li>
        <% end %>
        <li><%= link_to "Logout", '/logout', class: 'btn' %></li>
      <% else %>
        <li><%= link_to 'Login', '/auth/google_oauth2', class: 'btn' %></li>
      <% end %>
      </ul>
      <h3><%= image_tag("logo.png", alt: "Logo", class: "logo") %> <b>Hipster</b> </h3>
    </div>
    <%= yield %>
  </div>
  <br/>
</body>
</html>

app/views/layouts/webhook.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hipster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="logo.png">
</head>
<body class="frame">

    <div class="masthead">
      <ul class="nav nav-pills pull-right">
        <li class="webhook-callback"><strong>Copy this url into Web Hook URL bellow: </strong><code>
          <%= if callback_project_url(@project).include? "hipster.icehousecorp.com"
                callback_project_url(@project).sub("hipster.icehousecorp.com", "hipster.icehousecorp.com:8000")
              else
                callback_project_url(@project)
              end
          %>

        </code></li>
        <li><%= link_to "Next", detail_project_path, class: 'btn' %></li>
      </ul>
      <h3><%= image_tag("logo.png", alt: "Logo", class: "logo") %> <b>Hipster</b> </h3>
    </div>

    <iframe src="https://www.pivotaltracker.com/projects/<%= @project.pivotal_project_id %>/integrations#webhook_settings"></iframe>

</body>
</html>